name: Job Fetcher

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: 

jobs:
  fetch-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.1' 

      - name: Install dependencies
        run: npm install

      - name: Run the job fetcher script
        run: node app.js
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
