name: amazonJob

on:
  schedule:
    - cron: '0 */2 * * *' # Runs every 2 hours
  workflow_dispatch:

jobs:
  docker-job:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t rohith709370/amz .

      - name: Log in to Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: rohith709370
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push rohith709370/amz:latest

      - name: Stop and remove existing container
        run: |
          docker stop amz_container || true
          docker rm amz_container || true

      - name: Run Docker container with latest image
        run: docker run -d --name amz_container rohith709370/amz:latest

      - name: Wait for the container to start
        run: sleep 10

      - name: Fetch and display Docker logs
        run: docker logs -f amz_container
