name: Job Fetcher

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:

jobs:
  fetch-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: '20.15.1'

      - name: Install dependencies
        run: npm install

      - name: Run the job fetcher script
        run: node app.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Updated to use DISCORD_TOKEN